<a href="https://colab.research.google.com/github/sai2290/GEN_AI/blob/main/lstmTextprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras
from numpy import array
from tensorflow.keras.utils import to_categorical
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.text import Tokenizer
from keras.layers.core import Dense
from keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

In [ ]:
!pip install tensorflow==2.8.3

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.5/498.5 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 61.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 53.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 99.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.3/462.3 kB 29.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 85.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 44.2 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 2.12.0
    Uninstalling keras-2.12.0:
      Successfully uninstalled keras-2.12.0
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
 

In [ ]:
#source input text
inputdata="""Chandrayaan-3 consists of an indigenous propulsion module, lander module, and a rover with an objective of developing and demonstrating new technologies required for inter-planetary missions. The propulsion module will carry the lander and rover from injection orbit to till 100 km lunar orbit."""

In [ ]:
#integer encoding
tokenizer = Tokenizer()
tokenizer.fit_on_texts([inputdata])
encoded_data=tokenizer.texts_to_sequences([inputdata])[0]
encoded_data

[10,
 11,
 12,
 3,
 4,
 13,
 5,
 1,
 6,
 1,
 2,
 14,
 7,
 15,
 4,
 16,
 3,
 17,
 2,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 8,
 5,
 1,
 26,
 27,
 8,
 6,
 2,
 7,
 28,
 29,
 9,
 30,
 31,
 32,
 33,
 34,
 9]

In [ ]:
vocab_size=len(tokenizer.word_index)+1
vocab_size

35

In [ ]:
#sequence the word to fit the model
sequences = list()
for i in range(1,len(encoded_data)):
    sequence = encoded_data[i-1:i+1]
    sequences.append(sequence)


In [ ]:
sequences


[[10, 11],
 [11, 12],
 [12, 3],
 [3, 4],
 [4, 13],
 [13, 5],
 [5, 1],
 [1, 6],
 [6, 1],
 [1, 2],
 [2, 14],
 [14, 7],
 [7, 15],
 [15, 4],
 [4, 16],
 [16, 3],
 [3, 17],
 [17, 2],
 [2, 18],
 [18, 19],
 [19, 20],
 [20, 21],
 [21, 22],
 [22, 23],
 [23, 24],
 [24, 25],
 [25, 8],
 [8, 5],
 [5, 1],
 [1, 26],
 [26, 27],
 [27, 8],
 [8, 6],
 [6, 2],
 [2, 7],
 [7, 28],
 [28, 29],
 [29, 9],
 [9, 30],
 [30, 31],
 [31, 32],
 [32, 33],
 [33, 34],
 [34, 9]]

In [ ]:
# split x and y
sequences = array(sequences)
x,y=sequences[:,0],sequences[:,1]

In [ ]:
y=to_categorical(y,num_classes=vocab_size)

In [ ]:
y[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]], dtype=float32)

model = Sequential()
model.add(Embedding(vocab_size,8 ,input_length=1)
model.add(LSTM(50))
model.add(Dense(vocab_size,activation='softmax'))
print(model.summary())

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=1))
model.add(LSTM(100))
model.add(Dense(vocab_size,activation='softmax'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 1, 10)             350       
                                                                 
 lstm_7 (LSTM)               (None, 100)               44400     
                                                                 
 dense_7 (Dense)             (None, 35)                3535      
                                                                 
Total params: 48,285
Trainable params: 48,285
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(x,y,epochs=100)

Epoch 1/100
2/2 [==============================] - 0s 27ms/step - loss: 3.5558 - accuracy: 0.0227
Epoch 2/100
2/2 [==============================] - 0s 27ms/step - loss: 3.5543 - accuracy: 0.0227
Epoch 3/100
2/2 [==============================] - 0s 28ms/step - loss: 3.5531 - accuracy: 0.0682
Epoch 4/100
2/2 [==============================] - 0s 26ms/step - loss: 3.5520 - accuracy: 0.0682
Epoch 5/100
2/2 [==============================] - 0s 31ms/step - loss: 3.5510 - accuracy: 0.0682
Epoch 6/100
2/2 [==============================] - 0s 32ms/step - loss: 3.5498 - accuracy: 0.0682
Epoch 7/100
2/2 [==============================] - 0s 37ms/step - loss: 3.5486 - accuracy: 0.0682
Epoch 8/100
2/2 [==============================] - 0s 31ms/step - loss: 3.5476 - accuracy: 0.0682
Epoch 9/100
2/2 [==============================] - 0s 38ms/step - loss: 3.5463 - accuracy: 0.0682
Epoch 10/100
2/2 [==============================] - 0s 31ms/step - loss: 3.5452 - accuracy: 0.0909
Epoch 11/100
2/2 [=

In [ ]:
x

array([10, 11, 12,  3,  4, 13,  5,  1,  6,  1,  2, 14,  7, 15,  4, 16,  3,
       17,  2, 18, 19, 20, 21, 22, 23, 24, 25,  8,  5,  1, 26, 27,  8,  6,
        2,  7, 28, 29,  9, 30, 31, 32, 33, 34])

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
 n_pred=3


In [ ]:
def generate_seq(model,tokenizer,enter_text,n_pred):
  in_text,result=enter_text,enter_text
  for i in range (n_pred):
    encoded =tokenizer.texts_to_sequences([in_text])[0]
    encoded=array(encoded)
    # Reshape the input to match the expected shape by the model
    encoded = encoded.reshape(1, -1)
    # Check if the encoded sequence is empty and handle it
    if encoded.size == 0:
      print("Warning: Empty sequence encountered. Skipping prediction.")
      continue  # Skip to the next iteration
    y_prob = model.predict(encoded)
    yhat = y_prob.argmax(axis=-1)
   # yhat=model.predict_classes(encoded)
    out_word= ''
    for word,index in tokenizer.word_index.items():
        if index == yhat:
          out_word=word
          break
    in_text,result=out_word,result+''+out_word
  return result

# Enable eager execution if necessary
import tensorflow as tf
tf.config.run_functions_eagerly(True)

print(generate_seq(model,tokenizer,'image',2))

image
